%% Mermaid.js Mindmap docs: https://mermaid.js.org/syntax/mindmap.html %%
mindmap
	Autogen Script
		[Interface]
			[Fields]
				(text : Expansion pack name)
				("text : prefix (such as 'M' for metric screws or '#' for imperial)")
				(bool : length)
					(text : min)
					(text : max)
				(bool : outer diameter)
					(text : min)
					(text : max)
				(bool : inner diameter)
					(text : min)
					(text : max)
				(bool : overwrite existing files?)
		Script utilities
			class : Timer
				methods
					(start<br>Start or restart the timer<br>set last recorded time to 0)
					(stop<br>Stop the timer and save the last recorded time)
					(pause<br>pause the timer and don't update last recorded time until resume is called)
					(resume<br>Resume the timer and continue updating the last recorded time)
					(lap<br>save the last recorded time, restart timer.)
			("logger (important for testing and debugging)")
				[logger writes to debug.log file]
				[logger should be globally accessible]
		Fusion 360
			Variables
				))Variables should be refactored to better reflect what they represent((
				[Normal Label]
					("'M', inner diameter")
					("'Box_width', rename to 'bin_width'")
					("'bolt_length_l', length of bolt shaft, used when 'bool : length' is true")
					("'head_length_k', length of bolt head, used as general thickness for parts like washers")
					("'head_diameter_dk', diamter of bolt head, outer diamter")
		Divided Bins and Labels
			Divided Bins
				[write a script to generate a series of divided bins]
				[develop a set of rules for divisions]
					(there can't be more divisions than 2x the width of the bin)
			Divided labels
				[Divisions follow rules for divided bins]
				[It will have to have a different work flow compared to regular labels]
					id("(1) start by generating blank divided labels for all divided bins
					(2) to generate divided labels, add pictogram and text to divided label of choice
					(3) define generation rules for each division of label
					If using label with 3 divisions for screw lengths, the first label is
					|10mm|11mm|12mm|
					the second label should be
					|13mm|14mm|15mm|")
				Interface
					[button : add division]
		{{Problems/Isuues to solve}}
			)How to adapt the script to make generating labels for parts like bearings where sizes are not linear and each size has a standard name like 688, 608, etc. <br> *if possible*(
					