mindmap
	root(development plan)
		timer
			[create a timer class that 
			includes everything needed 
			to track time and allows 
			multiple instances to be 
			created and used]
		logger
		autgen options
			screw, bolt, washer
		[class "designParameter"]