    sequenceDiagram
    autonumber
    box Orange Fusion 360
    participant Design
    participant UI
    participant CommandInput
    end
    box LightBlue GLA Add-In
    participant APIInterface
    participant ParserValidator
    participant SciptLogic
    end
    Design-->>APIInterface: Get Design Parameters
    alt has gla_id
        APIInterface->>ParserValidator: Parse design parameters
    else does not have gla_id
        APIInterface-xUI: Use official GLA design
    end
    CommandInput-->>APIInterface: Get command parameters
    APIInterface->>ParserValidator: Validate command parameters
    loop Autogeneration Loop
        APIInterface-)SciptLogic: Run itteration
        SciptLogic-)ParserValidator: Validate itteration parameters
        ParserValidator-)APIInterface: Package itteration parameters
        APIInterface-)Design: Update design and export model
        Design-)APIInterface: Start loop over @6
    end

